DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): scriptflow.lamadon.com:80
DEBUG:urllib3.connectionpool:http://scriptflow.lamadon.com:80 "GET /test.php?hash=None&running=0&queued=0&completed=0&failed=0&retry=0 HTTP/1.1" 200 713
ERROR:root:Exception raised by task = <Task finished coro=<Controller.start_loops() done, defined at /Users/chaseabram/UChiGit/scriptflow/scriptflow/core.py:229> exception=FileNotFoundError(2, "No such file or directory: 'julia'")>
Traceback (most recent call last):
  File "/Users/chaseabram/UChiGit/scriptflow/scriptflow/cli.py", line 23, in _handle_task_result
    task.result()
  File "/Users/chaseabram/UChiGit/scriptflow/scriptflow/core.py", line 244, in start_loops
    self.update()
  File "/Users/chaseabram/UChiGit/scriptflow/scriptflow/core.py", line 164, in update
    exec.add(task)
  File "/Users/chaseabram/UChiGit/scriptflow/scriptflow/runners.py", line 57, in add
    stderr=subprocess.STDOUT)
  File "/Users/chaseabram/opt/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/chaseabram/opt/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'julia': 'julia'
